import type { Metadata } from "next";
import "./globals.css";
import "../components/themes/color.css";
import Header from "../components/layouts/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
