import type { Metadata } from "next";
import "./globals.css";
import "../components/themes/color.css";
import dayjs from "dayjs";
import "dayjs/locale/vi";
import { ConfigProvider } from "antd";
import viVN from "antd/locale/vi_VN";
import localizedFormat from "dayjs/plugin/localizedFormat";
import updateLocale from "dayjs/plugin/updateLocale";
dayjs.extend(localizedFormat);
dayjs.extend(updateLocale);
dayjs.locale("vi"); 

// Cập nhật tên thứ ngắn (Mon, Tue...) thành tiếng Việt nếu cần:
dayjs.updateLocale("vi", {
  weekdaysShort: ["CN", "T2", "T3", "T4", "T5", "T6", "T7"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={` antialiased`}>
        <main>
          <ConfigProvider locale={viVN}>{children}</ConfigProvider>
        </main>
      </body>
    </html>
  );
}
